complete -c problem -x -a home -d 'go to the problems home directory'
complete -c problem -x -a create  -d 'create a new problem'
complete -c problem -x -a known -d 'add a fact that has been learned'
complete -c problem -x -a question -d 'add a question to be answered'
complete -c problem -x -a test -d 'add a test to be performed'
complete -c problem -x -a idea -d 'add a hypothesis'
complete -c problem -x -a task -d 'add a task to be completed'
complete -c problem -x -a summarise -d 'bring together everything on one screen'
complete -c problem -x -a save -d 'save all changes to local git remo'
complete -c problem -x -a sync -d 'save changes then push ro remote repo'
complete -c problem -x -a consolidate -d 'bring all changes together in a single file'
